### ISSUE TITLE
Drilldown bar/column error

### ISSUE THREAD

**Issue by Alicia-Sydney** [datainsider-co/rocket-bi-service#1]
<img width="1042" alt="Screen Shot 2020-12-08 at 2 51 17 PM" src="https://user-images.githubusercontent.com/75656436/101440037-fdf56800-3969-11eb-9f07-8aa802bf3739.png">
<img width="1042" alt="Screen Shot 2020-12-08 at 3 15 37 PM" src="https://user-images.githubusercontent.com/75656436/101440044-0188ef00-396a-11eb-8dc8-cdca29c72b52.png">

**Comment by dnsang** [comment]
@nkthien I will buy you a ☕ if you get it done by tomorrow, or you get your self a ⚰️ 🤣

**Comment by nkthien** [comment]
Done
